import Head from "next/head";
// import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { Auth, ThemeSupa } from "@supabase/auth-ui-react";
import { useSession, useDescope } from "@descope/react-sdk";
import TodoList from "@/components/TodoList";
import dynamic from "next/dynamic";

const DescopeWC = dynamic(
  async () => {
    const { Descope } = await import("@descope/react-sdk");
    return (props: React.ComponentProps<typeof Descope>) => (
      <Descope {...props} />
    );
  },
  {
    ssr: false,
  }
);

export default function Home() {
  const { isAuthenticated } = useSession();
  const { logout } = useDescope();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-gray-200">
        {!isAuthenticated ? (
          <div className="min-w-full min-h-screen flex items-center justify-center">
            <div className="w-full h-full flex justify-center items-center p-4">
              <div className="w-full h-full sm:h-auto sm:w-2/5 max-w-sm p-5 bg-white shadow flex flex-col text-base">
                <span className="font-sans text-4xl text-center pb-2 mb-1 border-b mx-4 align-center">
                  Login
                </span>
                <DescopeWC
                  flowId={
                    process.env.NEXT_PUBLIC_DESCOPE_FLOW_ID || "sign-up-or-in"
                  }
                />
              </div>
            </div>
          </div>
        ) : (
          <div
            className="w-full h-full flex flex-col justify-center items-center p-4"
            style={{ minWidth: 250, maxWidth: 600, margin: "auto" }}
          >
            <TodoList />
            <button
              className="btn-black w-full mt-12"
              onClick={async () => {
                const { error } = await logout();
                if (error) console.log("Error:", error);
              }}
            >
              Logout
            </button>
          </div>
        )}
      </div>
    </>
  );
}
